### ISSUE TITLE
open doesn't use arguments/options

### ISSUE THREAD

**Issue by jsilverMDX** [infinitered/bluepotion#101]
if you look here https://github.com/infinitered/bluepotion/blob/70007244adc1a0c03924cd015104b30ac9e79ac6/lib/project/pro_motion/activities/pm_navigation_activity.rb#L26-L33

you can see nothing is done with the options

my current work around is to init the object, change the property and then call open

**Comment by jamonholmgren** [comment]
You're right. Should definitely be fixed. Seems like a straightforward pull request...want to give it a go, @jsilverMDX ? Something like:

```ruby
options.keys.each{|k| frag.send("#{k}=", options[k]) if frag.respond_to?("#{k}=") }
```

**Comment by jsilverMDX** [comment]
Yes, I will make a demo app and try to fix this before work today.

**Comment by jsilverMDX** [comment]
Thanks @Jamon.

**Comment by jamonholmgren** [comment]
:+1:

**Comment by jsilverMDX** [comment]
seems fixed to me.
