### ISSUE TITLE
PM::TableViewCell functionality

### ISSUE THREAD

**Issue by skellock** [infinitered/bluepotion#38]
As discussed offline with ye olde @GantMan, any chance of sneaking ProMotion's Table Cell functionality in?  Our app is heavy-custom-cells in iOS.  

Even starting with a blank cell view & stylesheet would :+1: and enough to get me going.

Exciting times!

**Comment by GantMan** [comment]
making great progress on this.

**Comment by skellock** [comment]
Thank you for your hard work.  I've got this up & running in our app.  :+1:

**Comment by GantMan** [comment]
:shipit:
