### ISSUE TITLE
PMNavigationActivity fragment changing signals

### ISSUE THREAD

**Issue by skellock** [infinitered/bluepotion#44]
It'd be great to support something `on_appear` & `on_return` when tapping back inside a navigation activity.

I'll put some something quick & dirty in place up at the project level for now.

**Comment by GantMan** [comment]
try `on_start` and let me know if that works.

**Comment by skellock** [comment]
It does.  Thanks, I'll be able to use that.  Interestingly, `on_load` fires too when back tracking.  Not sure if that's expected or not.

**Comment by jamonholmgren** [comment]
Actually, `on_return` should work.

https://github.com/infinitered/bluepotion/blob/8d606df154daff881086a7008007caf2212ff44c/lib/project/pro_motion/fragments/pm_screen_module.rb#L190

And `on_appear` is an alias for `on_start`.
