### ISSUE TITLE
Extra backstack item -- hitting back results in blank screen

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/bluepotion#54]
> An extra state is pushed on the back stack.  So when I launch a new activity, if I immediately hit Back, I get a blank screen.  (this might be as simple as checking the backstack count > 0 before popping)

From @skellock .

**Comment by jamonholmgren** [comment]
Bare BluePotion app reproduces this issue.

**Comment by jamonholmgren** [comment]
@skellock Can you try branch `bugfix/issue-54` ?

```ruby
gem "bluepotion", github: "infinitered/bluepotion", branch: "bugfix/issue-54"
```

**Comment by jamonholmgren** [comment]
The relevant change: deb006535970b3d9ead3331c43f7dcae4fec9ef7

I am almost certain I added this at some point, but it must have been lost somewhere in various branches.

**Comment by skellock** [comment]
You got it!  Thanks Jamon.
