### ISSUE TITLE
Dialog with Text Dialog Unexpected Id

### ISSUE THREAD

**Issue by skellock** [infinitered/bluepotion#58]
I'm trying to fire up an `app.alert` with a text box and the app crashes

```Exception raised: NameError: uninitialized constant `Alert_edit_text'```

BluePotion is looking for ```R::Id::Alert_edit_text``` but our app hasn't defined that.

https://github.com/infinitered/bluepotion/blob/master/lib/project/alert_dialog/alert_dialog.rb#L68

What's the best strategy here?  Should I define that constant in the app?  Should we pass it in as part of the interface?  Can BP autogen it?

Thanks in advance.

**Comment by GantMan** [comment]
Hrmmm.  Checking into this now.
