### ISSUE TITLE
Cannot find() controls after hitting back in PMNavigationActivity

### ISSUE THREAD

**Issue by skellock** [infinitered/bluepotion#59]
This is a strange one.

I have a `PMNavigationActivity`.  On it I have several `PMScreen`s.  I use `PMScreen#open` to flow forward through them.

On screen 1 I have some controls that I use `find(:foo)` in the `on_load` to attach event handlers.  Works great.  Same as page 2.  No problem.

When i go back to page 1, `on_load` fires again, but this time around `find(:foo)` returns 0 selectors.  The control is still inflated properly, it's just untargetable via `find`.

This used to work though, so something just recently unhooked it.

I've tried with & without `RMQ.caching_enabled`.

Bonus Round:  It'd be awesome if `on_return` worked too when I hit back.  Perhaps I'm going back wrong though.

**Comment by GantMan** [comment]
Def one to talk through with @twerth

**Comment by skellock** [comment]
Well done.
