### ISSUE TITLE
Pull To Refresh Support

### ISSUE THREAD

**Issue by skellock** [infinitered/bluepotion#64]
I typed:
```
class GantScreen < PM::TableScreen
  refreshable
end
```

And DalvikVM was like:
![](http://media.giphy.com/media/oFBKfk1aBK58s/giphy.gif)

**Comment by GantMan** [comment]
![working on it](http://i.imgur.com/Uu7errd.gif)

**Comment by GantMan** [comment]
for posterity on others who cross this issue:  https://github.com/infinitered/bluepotion/pull/77
