### ISSUE TITLE
Open Browser and Open Email Support

### ISSUE THREAD

**Issue by skellock** [infinitered/bluepotion#66]
I like the `sms` addition.

https://github.com/infinitered/bluepotion/blob/master/lib/project/pro_motion/pm_application.rb#L120

Can you hook us up with 2 more?

1. open an external web address (http://giphy.com)
2. open an email address (your@mom.com)

Thanks!

**Comment by GantMan** [comment]
better than your@mom.biz amirite!?

**Comment by GantMan** [comment]
Gonna do it like so:
```
app.launch(sms: '5044898008')
app.launch(email: 'your@mom.com')
app.launch(web: 'http://giphy.com')
```

**Comment by skellock** [comment]
Nice.

Would you support for `addExtra`?  Asking for a friend.
