### ISSUE TITLE
Base adapter is choosing the wrong view to recycle.

### ISSUE THREAD

**Issue by skellock** [infinitered/bluepotion#71]
I'm having some problems with the cell reuse functionality of the base adapter.  It's getting confused when I reload the list.

What's happening is I'm getting false positive matches.  For example, my header is getting chosen to present a data item.

I think this is caused from the `cell type` auto-generation logic.

I'm actually thinking it might not be possible to auto generate the view types.

The problem is:  the adapter needs to know all possible cell types that could ever go into the list.  Not just the ones that are there now.  (`getItemViewCount` never gets called more than once!).

So let's say i have a list of things:   `[HeaderCell, UserCell, UserCell]`.  No problem, the right thing happens.

But if the adapter starts off life like this:  `[NoUsersAddedYetCell]`, the adapter say, "Got it!  1 Cell only".   When you swap the underlying adapter data, hilarity ensues.

For now, the workaround I'm going to use is to manually unhook the adapter and recreate another one when the dataset changes.  It's slow and you lose your scroll position, but the views are correct.

**Comment by GantMan** [comment]
In those rare situations where you know there will be a new view type we can add some kind of syntax to add to our internal collection: so `getViewTypeCount`  and `getItemViewType` behave as planned.

Essentially the auto-generation logic can be in place _as-is_ for 90% of lists, and those who may dynamically load more will be required to identify their needs ahead of time.

**Comment by skellock** [comment]
Here's an example.

In this version, it actually crashes when you scroll.

https://github.com/skellock/bluepotion/blob/reuse-shenanignas/app/screens/example_custom_table_cells_screen.rb

Steps To Reproduce:

1.  Load the example app
2.  click "Open Table With Custom Cells"
3.  click any red cell to inject the poison!
4.  scroll
5.  read cryptic error message `Java.lang.ArrayIndexOutOfBoundsException: length=2; index=2`

**Comment by GantMan** [comment]
This is now solved simply with one line:
![screen shot 2015-08-10 at 2 12 19 pm](https://cloud.githubusercontent.com/assets/997157/9181245/1eb5afb4-3f6a-11e5-8806-0ad7d84d2fe4.png)

**Comment by GantMan** [comment]
@twerth this is a key item we should document at some point.
