### ISSUE TITLE
Stylesheet root_view is now required?

### ISSUE THREAD

**Issue by skellock** [infinitered/bluepotion#76]
Not sure if this was an accident or by design... no biggie either way.

It seems we're now required stylesheets to have a `def root_view(st)`.  Should this remain optional or did this have to change with the new `PMListScreen` + xml layout feature?  

I didn't dig into why.  Just noticed something up in our app broke (and was easily fixed).

https://github.com/infinitered/bluepotion/blob/master/lib/project/pro_motion/fragments/pm_screen.rb#L56

**Comment by skellock** [comment]
The plot thickens.

https://github.com/infinitered/bluepotion/blame/master/lib/project/pro_motion/fragments/pm_screen.rb#L56

/cc @twerth

**Comment by twerth** [comment]
Yes, we require it if you have a stylesheet. In RedPotion too.

**Comment by skellock** [comment]
Roger.
