### ISSUE TITLE
Error cloning the template

### ISSUE THREAD

**Issue by myob** [infinitered/bluepotion#84]
I believe this problem once existed for Redpotion but a solution was found and implemented there.
When I try 'bluepotion create myApp', I get:
Cloning into ‘localdir>’…  
Permission denied (publickey).
fatal: Could not read from remote repository.

Could the same fix be moved over to Bluepotion?

**Comment by KCErb** [comment]
This seems similar to my issue from a little bit ago, here's my final comment / solution in that:

https://github.com/infinitered/bluepotion/issues/27#issuecomment-113605361

Perhaps it can help you? :)

**Comment by myob** [comment]
Sadly, that didn't help.  I do appreciate the pointer!
But I still get the
 Template Unable to clone git@github.com:infinitered/bluepotion-template.git
error when attempting 'bluepotion create myApp'

**Comment by skellock** [comment]
What happens when you

`motion create --template=git@github.com:infinitered/bluepotion-template.git myob-git`
`motion create --template=https://github.com/infinitered/bluepotion-template.git myob-https`

Does the 2nd one work, but the first one doesn't?

**Comment by myob** [comment]
Yes.  The 2nd works fine, the first results in:
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by skellock** [comment]
@squidpunch just patched us up in master.  I'll pester @twerth today to release a gem update.

If you need a quick fix now, you can edit the `bluepotion` command directly and make this change:

https://github.com/infinitered/bluepotion/pull/85/files

On my system, that file is located at:

`/Users/steve/.gem/ruby/2.2.2/gems/bluepotion-0.1.7/bin/bluepotion`

Chances are your name isn't steve though.

Thanks for the bug report!

**Comment by myob** [comment]
More than happy to help!  I remembered the problem from Redpotion, and it got fixed there.
I could hardly be happier with Redpotion and look forward to great things with Bluepotion as well.
I'm going to close the issue as the fix is in hand.  Thanks much!
